name: dperf
on: workflow_dispatch
jobs:
  dperf:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          apt-cache search '^gcc-[0-9]+$'
          sudo apt install gcc-14 && gcc --version
