name: dperf
on: workflow_dispatch
jobs:
  dperf:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check
        run: |
          uname -a
          curl -s ipinfo.io
          wget https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-aarch64.tgz
          tar -xvzf ookla-speedtest-1.2.0-linux-aarch64.tgz
          ./speedtest --accept-license --accept-gdpr
